services:
  wordpress:
    image: wordpress:6.5.3-php8.2-apache
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./plugins/wp-toll-comments/plugin:/var/www/html/wp-content/plugins/ddns-toll-comments
    depends_on:
      - db
  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - wp-db:/var/lib/mysql

volumes:
  wp-db:
