[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
ddns_anchor = "DVXF1pMghQnuVeUJuuXJAZGXCDwrhr19nN3hQjvhReMU"
ddns_registry = "D58DJ6VopJKZCJ2cppAJZUcHE1UFF1qruPiU3EP3WMqM"
ddns_quorum = "DqSgwiSrtjjMEHoHNYpLpyp92yjruBTt6u7CYyhzyEbK"
ddns_stake = "Ao1vX55CSLTMUoeWEtzfmjWufEUemwm4uL7XGZg1j2AV"
ddns_watchdog_policy = "GTJWP2Mxu8DqVLMY8PAuAC3EwQKnviKAg4JY4mwMqVnF"
ddns_stake_gov = "HrSpSTG1dg3vqszY4P3idJpw9zrSUJ63ATS1eDxyxjh4"
ddns_escrow = "EoAdi1RNEYXurdHGUbCnHKGc2DgvKyJqrLVMkXPNj7MR"
ddns_domain_rewards = "BTsZBPqu92LWeqtPHDoMDuDAhd3mHmiers3pwrH2r2Pe"
ddns_ns_incentives = "AsnMwghaaKanvcYSffPr9MgwfXJoYini3BzVjaPPVMoL"
ddns_rewards = "5jcbSwHWNzuSMY7iJJTeVaQtaT14gpu9x3RPeQ8ZhxJX"
ddns_operators = "4onCDt3BR47VbJDkHeiFPXg6H6HJtGLzMQXJ58ovrx5d"
ddns_miner_score = "CktwdmQXGar4qJKKPxFsPdKQ9RMM5joJhqxKtZC2KAf8"
ddns_names = "AkABCWonPtbj8vpxef5GGBMdtWbLTo4p4ZnLR8rjYigB"
ddns_cache_head = "943epY8PMFRQkzJGaqjS8wLexHnQxS2o1cNm4xU1UDGb"
ddns_rep = "F2Jdqby47WQaqD7hYWdx2Hsg7yQCVUB7wCMyYGRhZ2EY"
ddns_witness_rewards = "CxoBkEjwHDJWUX9DyURPNyu9hrv92TaUK2yTS9tFAPdC"

[programs.localnet]
ddns_anchor = "DVXF1pMghQnuVeUJuuXJAZGXCDwrhr19nN3hQjvhReMU"
ddns_registry = "D58DJ6VopJKZCJ2cppAJZUcHE1UFF1qruPiU3EP3WMqM"
ddns_quorum = "DqSgwiSrtjjMEHoHNYpLpyp92yjruBTt6u7CYyhzyEbK"
ddns_stake = "Ao1vX55CSLTMUoeWEtzfmjWufEUemwm4uL7XGZg1j2AV"
ddns_watchdog_policy = "GTJWP2Mxu8DqVLMY8PAuAC3EwQKnviKAg4JY4mwMqVnF"
ddns_stake_gov = "HrSpSTG1dg3vqszY4P3idJpw9zrSUJ63ATS1eDxyxjh4"
ddns_escrow = "EoAdi1RNEYXurdHGUbCnHKGc2DgvKyJqrLVMkXPNj7MR"
ddns_domain_rewards = "BTsZBPqu92LWeqtPHDoMDuDAhd3mHmiers3pwrH2r2Pe"
ddns_ns_incentives = "AsnMwghaaKanvcYSffPr9MgwfXJoYini3BzVjaPPVMoL"
ddns_rewards = "5jcbSwHWNzuSMY7iJJTeVaQtaT14gpu9x3RPeQ8ZhxJX"
ddns_operators = "4onCDt3BR47VbJDkHeiFPXg6H6HJtGLzMQXJ58ovrx5d"
ddns_miner_score = "CktwdmQXGar4qJKKPxFsPdKQ9RMM5joJhqxKtZC2KAf8"
ddns_names = "AkABCWonPtbj8vpxef5GGBMdtWbLTo4p4ZnLR8rjYigB"
ddns_cache_head = "943epY8PMFRQkzJGaqjS8wLexHnQxS2o1cNm4xU1UDGb"
ddns_rep = "F2Jdqby47WQaqD7hYWdx2Hsg7yQCVUB7wCMyYGRhZ2EY"
ddns_witness_rewards = "CxoBkEjwHDJWUX9DyURPNyu9hrv92TaUK2yTS9tFAPdC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
