[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.29.0"

[programs.localnet]
ddns_anchor = "2kE76PBfDwKvSsfBW9xMBxaor8AoEooVDA7DkGd8WVR1"

[programs.devnet]
ddns_anchor = "2kE76PBfDwKvSsfBW9xMBxaor8AoEooVDA7DkGd8WVR1"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "anchor test"
