[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
ddns_anchor = "Cfg6rAXyemB4hqzf7DMY2yM5eY1RUqPwwE5jmZeUZM1v"
ddns_registry = "GBANos76CB8XiW3phuiCuZFsNvAhE9eBH4p8xxtVidPb"
ddns_quorum = "aaWUWeNPMVDtwokCxXTmDHV9GUvDrf2kBTtGbZxUV7B"
ddns_stake = "NLhRanr3wJGyHmGVxJ9cvjPef1wrmeZZHARXjrKHknD"
ddns_watchdog_policy = "5jRL193F84p4L9GFZmNUneyuZ19zopzsmnGVqZBkxdYH"
ddns_stake_gov = "BXZtfMCFu3kR7XtV41Y75EKPH7mQijTXLYQi9L6a1mrD"
ddns_escrow = "ConB7NytXDkuuANxWzoNMSDqX5wW4W95PpF4c4aizLpi"
ddns_domain_rewards = "WcHA8hCPxfMB9MCs48k9PtLcmnvQiMe1dEVciP96LoA"
ddns_ns_incentives = "F7PcEsu8qR2vmvUv42E84rtu61QAZj4YWgH3sn1QYzwg"
ddns_rewards = "AN2kAs8RSPb5KzggSPPyoZk3UXSrKjPW6r6N2r5Ap5bm"
ddns_operators = "CVMKnGhHeBRU6UKfabGNHkRGJyp7dq7VMmEb9kNfu6G5"
ddns_miner_score = "4ynffPWNStFxWppizPrrdam91nsPmV3kKD75DjxjNxxP"
ddns_names = "8FdWvta8RmCtPqqK4QoszKxf5Pn5kDjk6fvQ1XbEbB9g"
ddns_cache_head = "DsVuh3GyKTNHAorGnMqcaWPLRH2u84hM153c9uF88s9M"
ddns_rep = "CLE3orPrN6Wd4L3p7Z4mga3nSQa8Z1d3Kd1kvnVENB9U"
ddns_witness_rewards = "3nJNSWdN5d3kihzPi5VzcGUL2psFuZgveSQAffg6bb5V"

[programs.localnet]
ddns_anchor = "Cfg6rAXyemB4hqzf7DMY2yM5eY1RUqPwwE5jmZeUZM1v"
ddns_registry = "GBANos76CB8XiW3phuiCuZFsNvAhE9eBH4p8xxtVidPb"
ddns_quorum = "aaWUWeNPMVDtwokCxXTmDHV9GUvDrf2kBTtGbZxUV7B"
ddns_stake = "NLhRanr3wJGyHmGVxJ9cvjPef1wrmeZZHARXjrKHknD"
ddns_watchdog_policy = "5jRL193F84p4L9GFZmNUneyuZ19zopzsmnGVqZBkxdYH"
ddns_stake_gov = "BXZtfMCFu3kR7XtV41Y75EKPH7mQijTXLYQi9L6a1mrD"
ddns_escrow = "ConB7NytXDkuuANxWzoNMSDqX5wW4W95PpF4c4aizLpi"
ddns_domain_rewards = "WcHA8hCPxfMB9MCs48k9PtLcmnvQiMe1dEVciP96LoA"
ddns_ns_incentives = "F7PcEsu8qR2vmvUv42E84rtu61QAZj4YWgH3sn1QYzwg"
ddns_rewards = "AN2kAs8RSPb5KzggSPPyoZk3UXSrKjPW6r6N2r5Ap5bm"
ddns_operators = "CVMKnGhHeBRU6UKfabGNHkRGJyp7dq7VMmEb9kNfu6G5"
ddns_miner_score = "4ynffPWNStFxWppizPrrdam91nsPmV3kKD75DjxjNxxP"
ddns_names = "8FdWvta8RmCtPqqK4QoszKxf5Pn5kDjk6fvQ1XbEbB9g"
ddns_cache_head = "DsVuh3GyKTNHAorGnMqcaWPLRH2u84hM153c9uF88s9M"
ddns_rep = "CLE3orPrN6Wd4L3p7Z4mga3nSQa8Z1d3Kd1kvnVENB9U"
ddns_witness_rewards = "3nJNSWdN5d3kihzPi5VzcGUL2psFuZgveSQAffg6bb5V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
