[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ddns_anchor = "9hwvtFzawMZ6R9eWJZ8YjC7rLCGgNK7PZBNeKMRCPBes"
ddns_quorum = "9gyHsemmJfujZEqH1o4VhefxvbUJFQkPko8ASAteX5YB"
ddns_registry = "5zg8CsxpRKyurnTg539wr2nVtS6zritQDTGy4uAUerdx"
ddns_domain_rewards = "7iFM5ZYPWpF2rK6dQkgeb4RLc2zTDnEgrTNVMp8n6s3m"
ddns_operators = "3Q5VCoAT4TZ9xMrpbt4jbN9LhHfihxGH3TiD6PmSqHhp"
ddns_rewards = "8GQJrUpNhCFodqKdhEvWub6pjTtgoXBtBZUqxeEDujAY"
ddns_stake = "6gT4zHNpU4PtXL4LRv1sW8MwkFu254Z7gQM7wKqnmZYF"

[programs.localnet]
ddns_anchor = "9hwvtFzawMZ6R9eWJZ8YjC7rLCGgNK7PZBNeKMRCPBes"
ddns_quorum = "9gyHsemmJfujZEqH1o4VhefxvbUJFQkPko8ASAteX5YB"
ddns_registry = "5zg8CsxpRKyurnTg539wr2nVtS6zritQDTGy4uAUerdx"
ddns_domain_rewards = "7iFM5ZYPWpF2rK6dQkgeb4RLc2zTDnEgrTNVMp8n6s3m"
ddns_operators = "3Q5VCoAT4TZ9xMrpbt4jbN9LhHfihxGH3TiD6PmSqHhp"
ddns_rewards = "8GQJrUpNhCFodqKdhEvWub6pjTtgoXBtBZUqxeEDujAY"
ddns_stake = "6gT4zHNpU4PtXL4LRv1sW8MwkFu254Z7gQM7wKqnmZYF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
