[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
ddns_anchor = "EJVVNdwBdZiEpA4QjVaeV79WPsoUpa4zLA4mqpxWxXi5"
ddns_registry = "5F8ERKfRyErAJginsuRD4bN1oVZYFpJS5RVCFi9shRS3"
ddns_quorum = "2PVfW3pT5q8gLSXi4VzAiB3JqJzowgvZW9akyXXANAE6"
ddns_stake = "FTeUikzSsLcr2U9WMhs7y5n4cLyjMwg59FB7wWmWYo86"
ddns_watchdog_policy = "Ct4gQ98PofJxca2HSQrfzd1Cohay4praM9dFF2L9jr1g"
ddns_stake_gov = "EeU6h3gUUVKJeBsGG77onyH9Sjbq87Uz976RYHt2pCPf"
ddns_escrow = "2it8BbaePYnGaKcBrT5fAk7uj2YWaGdKtqSPriervwtA"
ddns_domain_rewards = "CKuPPeJAM8GdfvVMvERxa7rXJcNYwEy2P7wevQ4tjja2"
ddns_ns_incentives = "J3rL2iuBB3LzvymJ92yRQbRV6biLFefBKh5UvHLBwEJ2"
ddns_rewards = "D2P9nj4aVS9GiWu4UoLeBtJxKwVfu7FXqnj76f1sKwBd"
ddns_operators = "6QpkisF6re7KM5XwiYv5mqRmsfPBAwFEK6tkRmMeSRL8"
ddns_miner_score = "GYexwqwG1WArm3uSRNpTxZPVwvAPqrJp7BVzECJmWJGH"
ddns_names = "BYQ68JftwZD2JEMXLAiZYYGMr6AD9cD9XznntA4v6Mjj"
ddns_cache_head = "HjCiKFJKnSvuUd8gN8NjiFPdiwRZSqDit7LMJzFt3Sck"
ddns_rep = "BS62AYwh5KuhTWoVHiDbpAhifK4SDC1FJtKaYw9bSKaE"
ddns_witness_rewards = "6dNEBRscCHZB7yHo1iPBktccUSN7P32eSvY1FQkPh7hd"
[programs.localnet]
ddns_anchor = "EJVVNdwBdZiEpA4QjVaeV79WPsoUpa4zLA4mqpxWxXi5"
ddns_registry = "5F8ERKfRyErAJginsuRD4bN1oVZYFpJS5RVCFi9shRS3"
ddns_quorum = "2PVfW3pT5q8gLSXi4VzAiB3JqJzowgvZW9akyXXANAE6"
ddns_stake = "FTeUikzSsLcr2U9WMhs7y5n4cLyjMwg59FB7wWmWYo86"
ddns_watchdog_policy = "Ct4gQ98PofJxca2HSQrfzd1Cohay4praM9dFF2L9jr1g"
ddns_stake_gov = "EeU6h3gUUVKJeBsGG77onyH9Sjbq87Uz976RYHt2pCPf"
ddns_escrow = "2it8BbaePYnGaKcBrT5fAk7uj2YWaGdKtqSPriervwtA"
ddns_domain_rewards = "CKuPPeJAM8GdfvVMvERxa7rXJcNYwEy2P7wevQ4tjja2"
ddns_ns_incentives = "J3rL2iuBB3LzvymJ92yRQbRV6biLFefBKh5UvHLBwEJ2"
ddns_rewards = "D2P9nj4aVS9GiWu4UoLeBtJxKwVfu7FXqnj76f1sKwBd"
ddns_operators = "6QpkisF6re7KM5XwiYv5mqRmsfPBAwFEK6tkRmMeSRL8"
ddns_miner_score = "GYexwqwG1WArm3uSRNpTxZPVwvAPqrJp7BVzECJmWJGH"
ddns_names = "BYQ68JftwZD2JEMXLAiZYYGMr6AD9cD9XznntA4v6Mjj"
ddns_cache_head = "HjCiKFJKnSvuUd8gN8NjiFPdiwRZSqDit7LMJzFt3Sck"
ddns_rep = "BS62AYwh5KuhTWoVHiDbpAhifK4SDC1FJtKaYw9bSKaE"
ddns_witness_rewards = "6dNEBRscCHZB7yHo1iPBktccUSN7P32eSvY1FQkPh7hd"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
