[features]
seeds = false
skip-lint = false

[programs.localnet]
ddns_anchor = "2kE76PBfDwKvSsfBW9xMBxaor8AoEooVDA7DkGd8WVR1"

[programs.devnet]
ddns_anchor = "2kE76PBfDwKvSsfBW9xMBxaor8AoEooVDA7DkGd8WVR1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

[toolchain]
anchor_version = "0.32.1"
