[features]
seeds = false
skip-lint = false

[programs.localnet]
ddns_anchor = "9hwvtFzawMZ6R9eWJZ8YjC7rLCGgNK7PZBNeKMRCPBes"
ddns_miner_score = "37yrHgDgALGe4fUwWhJigQfD95jPFd9g2fDuYHkPAYaS"

[programs.devnet]
ddns_anchor = "9hwvtFzawMZ6R9eWJZ8YjC7rLCGgNK7PZBNeKMRCPBes"
ddns_miner_score = "37yrHgDgALGe4fUwWhJigQfD95jPFd9g2fDuYHkPAYaS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.32.1"
