[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
ddns_anchor = "9hwvtFzawMZ6R9eWJZ8YjC7rLCGgNK7PZBNeKMRCPBes"
ddns_registry = "5zg8CsxpRKyurnTg539wr2nVtS6zritQDTGy4uAUerdx"
ddns_quorum = "9gyHsemmJfujZEqH1o4VhefxvbUJFQkPko8ASAteX5YB"
ddns_stake = "6gT4zHNpU4PtXL4LRv1sW8MwkFu254Z7gQM7wKqnmZYF"
ddns_watchdog_policy = "6iveVkjqRiVpbSM3GmktMhGvqN7WConK5NrM6tvRZnnc"
ddns_stake_gov = "86XQF9V51Z8L8MLUP7yMU6ZWPzfaK1nhFsr3Hd8mYFgt"
ddns_escrow = "4jtDN5gqUqpmu1nBfLwPBAz8jBYjP6Nba4yZ8Am75M2J"
ddns_domain_rewards = "7iFM5ZYPWpF2rK6dQkgeb4RLc2zTDnEgrTNVMp8n6s3m"
ddns_ns_incentives = "8mC8Kvky9Jir4Lxe5R5L6ppoexaYtDJKe8JP8xA9JUuM"
ddns_rewards = "8GQJrUpNhCFodqKdhEvWub6pjTtgoXBtBZUqxeEDujAY"
ddns_operators = "3Q5VCoAT4TZ9xMrpbt4jbN9LhHfihxGH3TiD6PmSqHhp"
ddns_miner_score = "37yrHgDgALGe4fUwWhJigQfD95jPFd9g2fDuYHkPAYaS"
ddns_cache_head = "J3LCbeg9ocpGcGWdAAFjM8N4G7FTU9na1Lhe5VHBivZt"
ddns_rep = "FAPdRsatJoucFL6h1XQAQnQYN9KRxp7m2vzLLwnNmuLb"

[programs.localnet]
ddns_anchor = "9hwvtFzawMZ6R9eWJZ8YjC7rLCGgNK7PZBNeKMRCPBes"
ddns_registry = "5zg8CsxpRKyurnTg539wr2nVtS6zritQDTGy4uAUerdx"
ddns_quorum = "9gyHsemmJfujZEqH1o4VhefxvbUJFQkPko8ASAteX5YB"
ddns_stake = "6gT4zHNpU4PtXL4LRv1sW8MwkFu254Z7gQM7wKqnmZYF"
ddns_watchdog_policy = "6iveVkjqRiVpbSM3GmktMhGvqN7WConK5NrM6tvRZnnc"
ddns_stake_gov = "86XQF9V51Z8L8MLUP7yMU6ZWPzfaK1nhFsr3Hd8mYFgt"
ddns_escrow = "4jtDN5gqUqpmu1nBfLwPBAz8jBYjP6Nba4yZ8Am75M2J"
ddns_domain_rewards = "7iFM5ZYPWpF2rK6dQkgeb4RLc2zTDnEgrTNVMp8n6s3m"
ddns_ns_incentives = "8mC8Kvky9Jir4Lxe5R5L6ppoexaYtDJKe8JP8xA9JUuM"
ddns_rewards = "8GQJrUpNhCFodqKdhEvWub6pjTtgoXBtBZUqxeEDujAY"
ddns_operators = "3Q5VCoAT4TZ9xMrpbt4jbN9LhHfihxGH3TiD6PmSqHhp"
ddns_miner_score = "37yrHgDgALGe4fUwWhJigQfD95jPFd9g2fDuYHkPAYaS"
ddns_cache_head = "J3LCbeg9ocpGcGWdAAFjM8N4G7FTU9na1Lhe5VHBivZt"
ddns_rep = "FAPdRsatJoucFL6h1XQAQnQYN9KRxp7m2vzLLwnNmuLb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
