[workspace]
resolver = "2"
members = [
  "programs/ddns_anchor",
  "programs/ddns_registry",
  "programs/ddns_quorum",
  "programs/ddns_stake",
  "programs/ddns_domain_rewards",
]

[patch.crates-io]
blake3 = { git = "https://github.com/BLAKE3-team/BLAKE3", tag = "1.5.5" }

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
